# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T14:50:54+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, RootModel, constr


class Datum(RootModel[constr(min_length=0)]):
    root: constr(min_length=0)


class JsonGetResponse(BaseModel):
    data: Optional[List[Datum]] = Field(None, min_length=1)
